sudo: true
language: node_js
node_js:
  - 12.16.3
os:
  - linux
before_install:
  - npm i -g npm@6.14.4 jest codecov
  - npm --version
install:
  - npm ci
  - npm run load-apps
before_script:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then npm run doc; fi
script:
  - ./.concourse/test.sh
deploy:

# deploy documentation
- provider: surge
  project: "./docs/translationCore"
  domain: docs.tc.unfoldingword.surge.sh
  skip_cleanup: true
  on:
    branch: develop
