name: Node CI

on:
  pull_request:
    branches:
      - master
      - develop
      - release-*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: neutrinog/concourse-tasks:latest
    env:
      CI: true

    steps:
    - name: Node version
      run: |
        node --version
        npm --version

    - name: Checkout codebase
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: npm install
      run: npm ci

    - name: npm test
      run: npm run ci-test

    - name: upload coverage
      run: ./node_modules/.bin/codecov -t ${{ secrets.CODECOV_TOKEN }}

    - name: npm lint
      run: npm run lint

  build-linux:
    name: Build Linux
    needs: test
    runs-on: ubuntu-latest
    container: neutrinog/concourse-tasks:latest
    env:
      TC_HELP_DESK_TOKEN: ${{ secrets.TC_HELP_DESK_TOKEN }}
      TC_HELP_DESK_EMAIL: ${{ secrets.TC_HELP_DESK_EMAIL }}
      APP_NAME: tC
      CI: true

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Read version and commit sha
        run: |
          echo "::set-env name=HASH::$(echo $GITHUB_SHA | cut -c1-7)"
          echo "::set-env name=APP_VERSION::$(node -p -e "require('./package.json').version")"

      - name: Set artifact name
        run: echo "::set-env name=ARTIFACT_NAME::$(echo "$APP_NAME-linux-x64-$APP_VERSION-$HASH.deb")"

      - name: Bundle environment variables
        run: |
          echo "TC_HELP_DESK_TOKEN=$TC_HELP_DESK_TOKEN" >> .env
          echo "TC_HELP_DESK_EMAIL=$TC_HELP_DESK_EMAIL" >> .env
          echo "BUILD=$HASH" >> .env

      - name: npm install
        run: npm ci

      - name: Download latest language names
        run: curl https://td.unfoldingword.org/exports/langnames.json > src/assets/langnames.json

      - name: Update resources
        run: npm run update-resources

      - name: build linux
        id: build
        run: |
          echo "Building $APP_VERSION-$HASH"
          ./node_modules/.bin/gulp build --linux
          ./node_modules/.bin/gulp release-linux-deb --out=../artifacts/$ARTIFACT_NAME

      - uses: actions/upload-artifact@v1
        name: Upload artifacts
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ../artifacts/

  build-windows:
    name: Build Windows
    needs: test
    runs-on: windows-latest
    env:
      TC_HELP_DESK_TOKEN: ${{ secrets.TC_HELP_DESK_TOKEN }}
      TC_HELP_DESK_EMAIL: ${{ secrets.TC_HELP_DESK_EMAIL }}
      APP_NAME: tC
      CI: true

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Read version and commit sha
        run:
          echo "::set-env name=HASH::$(node -p -e "'${{ github.sha }}'.substring(0, 7)")"
          echo "::set-env name=APP_VERSION::$(node -p -e "require('./package.json').version")"

      - name: Bundle environment variables
        run: |
          echo "TC_HELP_DESK_TOKEN=$TC_HELP_DESK_TOKEN" >> .env
          echo "TC_HELP_DESK_EMAIL=$TC_HELP_DESK_EMAIL" >> .env
          echo "BUILD=$HASH" >> .env
          cat .env

      - name: npm install
        run: npm ci

      - name: Download latest language names
        run: curl https://td.unfoldingword.org/exports/langnames.json > src/assets/langnames.json

      - name: Update resources
        run: npm run update-resources

      - name: build windows
        run: |
          echo "Building $APP_VERSION-$HASH"
          ./node_modules/.bin/gulp build --win
#     x64
      - name: Set x64 artifact name
        run: echo "::set-env name=ARTIFACT_X64::$(echo "${{ env.APP_NAME }}-win-x64-${{ env.APP_VERSION }}-${{ env.HASH }}.setup.exe")"

      - name: bundle x64 windows
        run: |
          echo "Generating executable ../artifacts/${{ env.ARTIFACT_X64 }}"
          ./node_modules/.bin/gulp release-win64 --out=../artifacts/${{ env.ARTIFACT_X64 }}

      - name: list directories
        run: |
          dir .
          dir ../
          dir ../artifacts

      - uses: actions/upload-artifact@v1
        name: Upload x64 artifacts
        with:
          name: ${{ env.ARTIFACT_X64 }}
          path: ../artifacts/
#     x32
      - name: Set x32 artifact name
        run: echo "::set-env name=ARTIFACT_X32::$(echo "${{ env.APP_NAME }}-win-x32-${{ env.APP_VERSION }}-${{ env.HASH }}.setup.exe")"

      - name: bundle x32 windows
        run: |
          echo "Generating executable ../artifacts/${{ env.ARTIFACT_X32 }}"
          ./node_modules/.bin/gulp release-win32 --out=../artifacts/${{ env.ARTIFACT_X32 }}

      - uses: actions/upload-artifact@v1
        name: Upload x32 artifacts
        with:
          name: ${{ env.ARTIFACT_X32 }}
          path: ../artifacts/

  build-macos:
    name: Build macOS
    needs: test
    runs-on: macos-latest
    env:
      TC_HELP_DESK_TOKEN: ${{ secrets.TC_HELP_DESK_TOKEN }}
      TC_HELP_DESK_EMAIL: ${{ secrets.TC_HELP_DESK_EMAIL }}
      APP_NAME: translationCore
      CI: true

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Read version and commit sha
        run: |
          echo "::set-env name=HASH::$(echo $GITHUB_SHA | cut -c1-7)"
          echo "::set-env name=APP_VERSION::$(node -p -e "require('./package.json').version")"

      - name: Set artifact name
        run: echo "::set-env name=ARTIFACT_NAME::$(echo "$APP_NAME-macos-x64-$APP_VERSION-$HASH.dmg")"

      - name: Bundle environment variables
        run: |
          echo "TC_HELP_DESK_TOKEN=$TC_HELP_DESK_TOKEN" >> .env
          echo "TC_HELP_DESK_EMAIL=$TC_HELP_DESK_EMAIL" >> .env
          echo "BUILD=$HASH" >> .env

      - name: npm install
        run: npm ci

      - name: Download latest language names
        run: curl https://td.unfoldingword.org/exports/langnames.json > src/assets/langnames.json

      - name: Update resources
        run: npm run update-resources

      - name: build macOS
        id: build
        run: |
          echo "Building $APP_VERSION-$HASH"
          ./node_modules/.bin/gulp build --macos
          ./node_modules/.bin/gulp release-macos --out=../artifacts/$ARTIFACT_NAME

      - uses: actions/upload-artifact@v1
        name: Upload artifacts
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ../artifacts/

  notify:
    name: Notify
#    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Get short hash
        run: |
          echo "::set-env name=HASH::$(echo $GITHUB_EVENT_AFTER | cut -c1-7)"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Notify Zulip of pull request
#        if: github.event_name == "pull_request"
        env:
          TOKEN: ${{ secrets.ZULIP_TOKEN }}
          USER: concourse-bot
          ORG: unfoldingword
          CHANNEL: SOFTWARE/github
          SUBJECT: tC builds
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.event.after }}
          PR_NUMBER: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          curl -o /dev/null -s -X POST https://$ORG.zulipchat.com/api/v1/messages \
            -u $USER@zulipchat.com:$TOKEN \
            -d "type=stream" \
            -d "to=$CHANNEL" \
            -d "subject=$SUBJECT" \
            -d "content=[$PR_TITLE #$PR_NUMBER](https://github.com/$REPOSITORY/pull/$PR_NUMBER) has new builds based on [$HASH](https://github.com/$REPOSITORY/pull/$PR_NUMBER/commits/$SHA).
                        You can view logs and download artifacts from the [Checks](https://github.com/$REPOSITORY/pull/$PR_NUMBER/checks?sha=$SHA) tab."
